### ISSUE TITLE
Support non-Amazon S3-compatible services

### ISSUE THREAD

**Issue by robinpellegrims** [bojanbass/nx-aws#1]
Would it be possible to extend this solution to support an S3-compatible API like Backblaze B2 or Wasabi? 

It seems the only thing missing is the ability to provide an endpoint variable in the configuration and pass it on when [creating the S3 object](https://github.com/bojanbass/nx-aws/blob/cc43ff28d304f06e2f214b23e3c093503cdb0343/packages/nx-aws-cache/src/tasks-runner/aws-cache.ts#L30). For backblaze this is explained [here](https://help.backblaze.com/hc/en-us/articles/360046980734-How-to-use-the-AWS-SDK-for-JavaScript-with-B2).

If you want I can provide a PR.

**Comment by bojanbass** [comment]
I have no experience with Backblaze B2 or Wasabi. It could be better to build another module like this one to support pluggable apis, as the name `nx-aws` woudn't be appropriate anymore. There was another module available for azure as well, but it looks like it was removed. I suppose there a licencing problems and I'm not even sure for this one if it's ok to be published. So I would rather think of removing it than extending with new features.
