### ISSUE TITLE
possibility to set custom AWS endpoint

### ISSUE THREAD

**Issue by lotterfriends** [bojanbass/nx-aws#12]
I use a self hosted aws, to use that I need the possibility to set the endpoint, otherwise *s3.eu-de.amazonaws.com* is always used
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientresolvedconfig.html#endpoint

**Comment by bojanbass** [comment]
Released in v1.0.2
