### ISSUE TITLE
Should all the peerDependencies be optional?

### ISSUE THREAD

**Issue by NullVoxPopuli** [bojanbass/nx-aws#128]
I saw that in the package.json, there are these `peerDependenies` entries:

```js
  "peerDependencies": {
    "@angular-devkit/core": ">=11.0.1",
    "@angular-devkit/schematics": ">=11.0.1",
    "@nrwl/workspace": ">=9.2.2"
  },
```

Since I don't use angular, and since nx14 does not need `@nrwl/workspace`, can all of these peers be optional?

Related: 
 - https://github.com/bojanbass/nx-aws/issues/127
 - https://github.com/bojanbass/nx-aws/issues/126

**Comment by bojanbass** [comment]
Hi. Thank you for reporting. Those are used only for backward NX compatibility, which was using those packages. Did you meant moving those dependencies to `optionalDependencies` or some other approach?

**Comment by jakemhiller** [comment]
Yeah, i'm interested in testing this out but I'm running into these errors. Might make sense to move them to `optionalDependencies` or remove them if that backwards compatibility isn't necessary anymore?

**Comment by jakemhiller** [comment]
actually, it looks like at least `@angular-devkit/schematics` is actually used in the plugin itself, so it can't be optional.

**Comment by bojanbass** [comment]
`@angular-devkit` was removed, please update to v2.0.0 and report if the issue is still present.
