### ISSUE TITLE
IAM roles

### ISSUE THREAD

**Issue by paddyfay** [bojanbass/nx-aws#2]
does this library support IAM roles? seems to always fail for me and falls back to using the default task runner.

the issue i see is checking the config in the AwsCache class
https://github.com/bojanbass/nx-aws/blob/8dd71942a3b73d5eca5f0947205574d607bb8797/packages/nx-aws-cache/src/tasks-runner/aws-cache.ts#L37
when using IAM roles `new S3().config.credentials` always returns null, hence `checkConfig` throws an error

i've tested IAM role support bypassing this check and everything seems to work as expected

**Comment by bojanbass** [comment]
Unfortunatelly not, there's only basic support for S3. Feel free to create a pull request for the change. I notices some forks of this repository already contain this logic.

**Comment by bojanbass** [comment]
Hi @paddyfay, I just released a new version which includes AWS SDK v3. Could you test and provide a feedback if IAM roles now work? I haven't tried to use it this way so I'm not sure it solves the problem.
