### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by maverick089** [bojanbass/nx-aws#213]
Hi,

thank you for this great project! 

Locally, it works perfectly for me, but I have been struggling to run it on AWS CodeBuild. It did not pickup the credentials correctly. The current version 1.1.0 uses  **fromIni** which is not working. Your current master already uses **fromNodeProviderChain** which works in AWS CodeBuild. 

Could you please publish a new version to npm that uses **fromNodeProviderChain**?

**Comment by bojanbass** [comment]
I will publish is as soon as I migrate some other code related to NX version. I have to do some testing, hopefully it would be finished soon.

**Comment by bojanbass** [comment]
Published v2.0.0.

**Comment by maverick089** [comment]
Wow, that was fast! Thank you very much! Tested it with AWS CodeBuild already and it works perfectly!

**Comment by bojanbass** [comment]
Great to hear!
