### ISSUE TITLE
Add an option for disabling the AWS Cache

### ISSUE THREAD

**Issue by dcherman** [bojanbass/nx-aws#359]
Right now, the only way of skipping the remote cache and using the local one is via the [NXCACHE_AWS_DISABLE environment variable](https://github.com/bojanbass/nx-aws/blob/250a32afc5f90921ed74a576aaaad15195b6b11d/packages/nx-aws-cache/src/tasks-runner/runner.ts#L37C54-L37C54).

Ideally, we would like to disable the remote cache by default for local development, but have it enabled for CI.  Since we need to set an environment variable to disable the cache, that'd mean we need `.env` support or using something like `crossenv` to set the environment var in a cross-os compatible way.

If we add this as an option, we could just do `nx build --skip-aws-cache=false` on CI and have the default value be true in our NX config.

Happy to make a PR if you think this would be acceptable.

**Comment by bojanbass** [comment]
Why wouldn't you just set `NXCACHE_AWS_DISABLE=true` in workspace root `.env` file and then in CI, set this variable globally `NXCACHE_AWS_DISABLE=false`. It's basically the same as using an argument. There's also an NX option to skip NX cache by using ENV variable: https://nx.dev/reference/environment-variables (`NX_SKIP_NX_CACHE`).

**Comment by dcherman** [comment]
Closing - that's actually exactly what we ended up doing.  I didn't realize that `NX` had built in support for loading from a variety of `.env` files until after I'd already filed this.  Thanks for the super quick response though!

**Comment by bojanbass** [comment]
That's great, you're welcome!
