### ISSUE TITLE
Allow to reuse cache generated on other machines

### ISSUE THREAD

**Issue by SebastianSedzik** [bojanbass/nx-aws#368]
### Problem
I'm running code on different nodes on CI pipeline execution.
During execution, an attempt of loading the remote cache ends up with the error, as nx does not allow the use of cache from different machines.

![Screenshot 2023-08-09 at 14 30 22](https://github.com/bojanbass/nx-aws/assets/30985766/3ac2a8db-f227-4cbd-b5dc-9105678727c3)

### Proposed solution
Extend config with `trustForeignMachineCache?: boolean` property, which will allow to reuse cache generated on machines different than current (by removing `source` file from downloaded `tar`).

### Workarounds
There is a [known workaround](https://nx.dev/recipes/troubleshooting/unknown-local-cache#you-share-cache-with-another-machine-using-a-network-drive) by setting `REJECT_UNKNOWN_LOCAL_CACHE=0` env variable, but this approach is discouraged. It should be the responsibility of `RemoteCache` provider (like `nx-aws`) instead of nx

Please share your POV about this idea. If you have no red flags, let me know and I will prepare a PR for that.

**Comment by Jefiozie** [comment]
Today I runner tk the exact same thing. I think that it makes sense to provide a option to remove the source from the downloaded file. 

Note: this check is added in one off the recent versions of NX.

**Comment by SebastianSedzik** [comment]
@bojanbass Does it also make sense for you?

**Comment by SebastianSedzik** [comment]
Bump @bojanbass, WDYT?

**Comment by bojanbass** [comment]
Hi @SebastianSedzik. I didn't know about this options, but is seems reasonable to add it as an option. Feel free to prepare a PR for it.

**Comment by SebastianSedzik** [comment]
@bojanbass I [created a PR](https://github.com/bojanbass/nx-aws/pull/376), please take a look if you will find some time :)

**Comment by ddivecs** [comment]
I believe there is also an ongoing issue on nrwl/nx about this. https://github.com/nrwl/nx/issues/18642#issuecomment-1684343374

**Comment by SebastianSedzik** [comment]
@ddivecs Thanks for the information (I was not aware of that)!
So it looks like it is an issue with nx rather than nx-aws. Let's wait for the [final decision in that discussion](https://github.com/nrwl/nx/issues/18642) to close this one.

**Comment by bojanbass** [comment]
Released in `v3.1.0`.
