### ISSUE TITLE
 readRootPackageJson is not a function during init

### ISSUE THREAD

**Issue by zachdixon** [bojanbass/nx-aws#448]
Hi, I'm trying out this package and ran into this issue while running init:

` NX   (0 , devkit_1.readRootPackageJson) is not a function`

From what I can tell, that function doesn't exist in the @nx/devkit package. Could be a version mismatch? Not sure, but mine is v16.9.1

I was able to fix/bypass it by changing it to use `readJsonFile('package.json')` instead

**Comment by bojanbass** [comment]
@zachdixon, would you please check the latest release version? The bug should be fixed now.
