### ISSUE TITLE
normalized windows paths in S3 storage

### ISSUE THREAD

**Issue by ChrisKeck** [bojanbass/nx-aws#455]
First of all, thank you very much for the plugin. 

Problem:
Unfortunately, I'm developing on a Windows computer and have a problem where "/" is normalized to "\" in this function https://github.com/bojanbass/nx-aws/blob/ddcc209d6a6f7612e0de30485edb865ed8cdbdb0/packages/nx-aws- cache/src/tasks-runner/aws-cache.ts#L247 . 

Possible Solution:
The easiest way is to insert a replace("\\","/") after the "join". This means that Windows can work properly and the files do not end up on the S3 storage from a Windows computer with “xyz\123.tar.gz”.

**Comment by Banegasn** [comment]
@ChrisKeck i just made a pr that fixes this problem, i think 
https://github.com/bojanbass/nx-aws/pull/501

**Comment by ChrisKeck** [comment]
PR looks good! Please merge it. Thank you!

**Comment by ardabeyazoglu** [comment]
Issue persists. Will it be merged?

**Comment by bojanbass** [comment]
This has been release in https://github.com/bojanbass/nx-aws/releases/tag/v3.2.2. Please check and close the issue if it's working correctly.

**Comment by ardabeyazoglu** [comment]
It works.
