### ISSUE TITLE
Issues with Latest NX and RxJS

### ISSUE THREAD

**Issue by knguyen0125** [bojanbass/nx-aws#9]
Using Latest NX version and RxJS causes the following issues:

```
$runner.subscribe is not a function
```

The issues is isolated to the latest version, and using the older 0.0.5 version with the same NX and RxJS still works.

I think it's because previous version wraps $runner in a from($runner), which creates an observable that can be subscribed.

**Comment by bojanbass** [comment]
Correct, I just noticed the same error after upgrading to the lastest NX version. Will prepare a fix for this. However I'm not sure what is the right way to support new NX version using @nrwl/devkit and the old one. I'm not so happy about using @angular-devkit as a dependency because it should be framework agnostic.

**Comment by lotterfriends** [comment]
@bojanbass  maybe you can do sth. like this in [packages/nx-aws-cache/src/tasks-runner/runner.ts] ?(https://github.com/bojanbass/nx-aws/commit/6d816577175951c2f2e0db3aee4c9b79bb002b18#diff-9e88f6756bdd73c57e6bcc0f5de16a70f6a63fcfb551a91cb2f12fdd321de91b) ?
```ts

const onRunner = {
    next: (value) => runnerWrapper.next(value),
    error: (err) => runnerWrapper.error(err),
    complete: async () => {
      await remoteCache.waitForStoreRequestsToComplete();
      messages.printMessages();
      runnerWrapper.complete();
    },
 };
if (typeof runner$?.subscribe === 'function') {
  runner$.subscribe(onRunner);
} else {
  from(runner$).subscribe(onRunner);
}
```

**Comment by bojanbass** [comment]
Yes, this could be a solution, even a simpler one is here: https://github.com/bojanbass/nx-aws/pull/10

**Comment by bojanbass** [comment]
Released https://github.com/bojanbass/nx-aws/releases/tag/v1.0.1. Could you try and report if the bug is still present?
